apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: content-config
    files:
      - index.html
secretGenerator:
  - name: secret-1
  - name: secret-2
patchesStrategicMerge:
  - secret-1.yaml
  - secret-2.yaml
