apiVersion: ENC[AES256_GCM,data:sWg=,iv:3lqfJ3uxK6rVG7G1TB+wCwEdl2lN95aYU+o3KJDUL8I=,tag:SEsFm9rEQNRnCehAwHR9+Q==,type:str]
kind: ENC[AES256_GCM,data:62oovP2D,iv:tDBR5fpH6ABrxnZJdjS99/A99eV4Xc5bYfsbJUGKtkU=,tag:R0uREnvfLqwLm3+gL2/F6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nzEnPlWYMKg=,iv:g6vswaHVBcRU1KK1cL8JEGBmQ938Jq1qpHPWlzQJrL0=,tag:R6pb4LeogRKCCcpilfARYg==,type:str]
type: ENC[AES256_GCM,data:RjA/+uol,iv:OhIXT/BsUOJhGNA+ADwoaF/fmSHzUeL+OoRbGm5EOZc=,tag:BEpX9Yw+Xrxyz0afrLn26Q==,type:str]
data:
    secret.txt: ENC[AES256_GCM,data:m0rFHlPkD+TFKY6vDFqdmMZx2xYcmhLbyeuMdf0Jfeu0d1gx,iv:owLQ303cHtvU/inLAYq+JQ48zAFBjKtV6AoOI0yfKC0=,tag:znmc+WAm1c4evunSZPEHJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-06-30T10:01:46Z'
    mac: ENC[AES256_GCM,data:Kp96KFmIQR3cYafkeTv/3XX1SXDLwlXPHJ9IwzPf6TqwxRbNoahk88ZN9/Trad4WXwLLLnQ2bDDvmhemNOX8vnmPW5VXmkJniTjTtuj31hqcdFP3doyS6l+ILaKXACQp1pFxp2ZBaMfMQ4snY7mDmqdX/5/8NcrYYP1snL4L39M=,iv:vqDTuIX2F6ndurH6Fx62QdVjsRKG/W0zVNZHQNeqaNw=,tag:OZo0mRybi6+3tY/o9LOSQA==,type:str]
    pgp:
    -   created_at: '2019-06-29T17:17:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9bGUdTaoZxKAQgAha31GGAm2xmcL5Gpjg2WnlxtE5yoKUtfPYM447Mw+C7R
            +tX5PjOpizrnp2nGppARob3PP4o7QYqfEZKTR8WVvOgb34pXcvJRXCrvff0kk1Vk
            1lvKDB2pOQoCZ/6wsq4N22sNEJbCw1g581quzyIOG+3yNwedb1nk/IXV78/8ts+/
            0LV3h0ffkTXH0c84AxP7mPXatFcKQDTiwOXrTnbznm4LJvYW2YvuydenDQvcE8Bv
            5ltZVSLkbYAzX6ucmbLJvUeVR7mPRCMpHEkq9AqWoZWxru1SGU8yCF2ZbZR3YT4l
            4k7paJHaYWQAjO2EJsPlL3NxBamrDruWfIIB6b5Vs9JcAbysiwSf6R2N5PTH/h4E
            /Eagz31ucll112a3bokM8/UEIC1Z6RLVFl+8R0V6gvMhY5xvPXMcqR9yPn8Y4oTi
            gnwIlxPpZ78hRGeaqLJKY1c09OpTMI//otOcTog=
            =Mtuz
            -----END PGP MESSAGE-----
        fp: 28A4E3742FF30047277C32E266C52CA05F3FB2E4
    unencrypted_suffix: _unencrypted
    version: 3.3.0
